apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Namespace }}-workshop-monitoring-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
subjects:
  - kind: ServiceAccount
    name: workshop
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workshop-token-creator
  namespace: {{ .Values.global.monitoringNamespace | default "monitoring" }}
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts/token"]
    resourceNames: ["monitoring-reader"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Namespace }}-workshop-token-creator
  namespace: {{ .Values.global.monitoringNamespace | default "monitoring" }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workshop-token-creator
subjects:
  - kind: ServiceAccount
    name: workshop
    namespace: {{ .Release.Namespace }}
