{{- if .Values.sandboxPrepull.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: sandbox-image-prepull
  namespace: {{ .Release.Namespace }}
spec:
  backoffLimit: 2
  ttlSecondsAfterFinished: 600
  template:
    spec:
      serviceAccountName: default
      restartPolicy: Never
      containers:
        - name: prepull
          image: {{ .Values.upstream.server.sandboxImage }}
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "exit 0"]
{{- end }}
