apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: monitoring-scc-privileged
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["security.openshift.io"]
    resources: ["securitycontextconstraints"]
    resourceNames: ["privileged"]
    verbs: ["use"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitoring-scc-privileged
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: monitoring-scc-privileged
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: kps-prometheus-node-exporter
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: kps-prometheus
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: kps-operator
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: kps-grafana
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: kps-kube-state-metrics
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: kps-alertmanager
    namespace: {{ .Release.Namespace }}
