image: quay.io/mmurakam/nemoclaw-workshop:v0.2.1
replicas: 1

inference:
  baseUrl: ""
  model: ""
  apiKey: ""

openclaw:
  agentName: shifty
  gatewayPassword: openclaw

openshellGateway:
  endpointUrl: "http://openshell.openshell.svc.cluster.local:8080"

grafana:
  origin: "http://grafana.monitoring.svc.cluster.local:80"

monitoring:
  promHost: "https://thanos-querier.openshift-monitoring.svc.cluster.local:9091"
  lokiHost: "https://logging-loki-gateway-http.openshift-logging.svc.cluster.local:8080"
  tempoHost: "https://tempo-tempostack-gateway.observability-hub.svc.cluster.local:8080"
