{{- $namespace := include "minio.namespace" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio.fullname" . }}
  namespace: {{ $namespace }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ .Values.minio.secret.user | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.secret.password | quote }}
