"use client";
import { useState, type ReactNode } from "react";

// Detailed, interactive "OpenShell on Kubernetes" deployment — modelled on the NVIDIA
// deck's architecture slide. Click any object to see what it is, plus how THIS launchable
// maps to it. Grouped by where things actually live: external clients, the openshell
// namespace (gateway + its state), the agent-sandbox controller, and the sandbox pods.

const NV = "#76b900", BLUE = "#6f8fd0", PURPLE = "#a78bfa", AMBER = "#e0a800",
      GREEN = "#34d399", SLATE = "#94a3b8", CYAN = "#22d3ee", RED = "#ef6b6b";

type N = { id: string; label: string; sub?: string; color: string; what: ReactNode; ours: ReactNode };

const NODES: Record<string, N> = {
  cli: { id: "cli", label: "CLI / SDK / TUI", sub: "openshell …", color: SLATE,
    what: <>The operator surface. <code>openshell gateway add</code>, <code>sandbox create</code>, <code>policy set</code>, <code>inference set</code>. Authenticates with an mTLS client cert + (optionally) an OIDC JWT.</>,
    ours: <>Installed in the workshop shell and registered against the gateway via the in-cluster Service (no OIDC in this dev setup).</> },
  oidc: { id: "oidc", label: "OIDC Identity Provider", sub: "Keycloak / Entra ID", color: AMBER,
    what: <>Issues JWTs with role claims so the gateway can do per-method authorization (admin vs read-only user). Powers the OpenShell Console login.</>,
    ours: <>Disabled for the workshop — the gateway runs with <code>allowUnauthenticatedUsers</code> so the CLI works with no SSO. Add Keycloak for multi-tenant.</> },
  grpcroute: { id: "grpcroute", label: "Route + Service", sub: "Route → Service :8080", color: BLUE,
    what: <>Inbound gRPC reaches the gateway through a Kubernetes <strong>Service</strong>, fronted by an OpenShift <strong>Route</strong> for external access with a hostname + TLS.</>,
    ours: <>An OpenShift <code>Route</code> provides external access; the in-cluster <code>openshell</code> CLI reaches the gateway via the ClusterIP Service.</> },
  gw: { id: "gw", label: "Gateway StatefulSet", sub: "API · state · policy · inference", color: NV,
    what: <>The control plane. Serves the gRPC API, stores provider creds, delivers policy, hosts the inference router, and <strong>authenticates each sandbox's supervisor over mTLS</strong>. StatefulSet on SQLite (or HA Deployment on Postgres).</>,
    ours: <>StatefulSet <code>openshell</code> (SQLite), image <code>gateway:0.0.70</code>, <code>disableTls</code> for simplicity. Its Kubernetes compute driver watches the Sandbox CRD.</> },
  pvc: { id: "pvc", label: "PVC", sub: "durable state", color: GREEN,
    what: <>Persists the gateway's SQLite DB (sandbox registry, policy revisions, provider config) across restarts.</>,
    ours: <>Bound via the cluster's default storage provisioner.</> },
  secrets: { id: "secrets", label: "Secrets", sub: "PKI + SSH handshake", color: RED,
    what: <>The gateway-minted sandbox-JWT signing keys + the mTLS PKI used for the supervisor handshake and exec/SSH relay.</>,
    ours: <>Generated by the <code>pkiInitJob</code> hook. We set <code>sandboxJwt.secretDefaultMode: 0444</code> so the random-UID gateway pod can read the signing key.</> },
  rbac: { id: "rbac", label: "RBAC", sub: "SA + Role bindings", color: PURPLE,
    what: <>The gateway + sandbox ServiceAccounts and their Roles — what the compute driver may do (create Sandboxes, read pods) and what each sandbox's SA may do.</>,
    ours: <>Plus OpenShift <strong>SCCs</strong>: <code>privileged</code> for <code>openshell-sandbox</code>, <code>anyuid</code> for the gateway/certgen SAs.</> },
  pki: { id: "pki", label: "pkiInitJob", sub: "cert bootstrap", color: CYAN,
    what: <>A pre-install hook (<code>openshell-gateway generate-certs</code>) that creates the server + client mTLS Secrets in-cluster — or cert-manager Issuers for auto-rotation.</>,
    ours: <>The built-in <code>pkiInitJob</code> (no cert-manager). We grant its SA <code>anyuid</code> so the hook Job schedules on OpenShift.</> },
  ctrl: { id: "ctrl", label: "agent-sandbox controller", sub: "agents.x-k8s.io · CRDs", color: BLUE,
    what: <>The kubernetes-sigs/agent-sandbox operator. Reconciles each <code>Sandbox</code> CR into a Pod (+ PVC), in its own <code>agent-sandbox-system</code> namespace.</>,
    ours: <>Pinned to <strong>v0.4.6</strong> (v1alpha1) — v0.5.0's v1beta1 ownerReferences break the gateway 0.0.70 ownership check.</> },
  pod: { id: "pod", label: "Sandbox Pod", sub: "supervisor + agent", color: PURPLE,
    what: <>Each sandbox is a Pod with the <strong>supervisor</strong> (sideloaded init-container) wrapping the <strong>agent</strong> container (OpenClaw, Claude Code, a custom claw…). The supervisor dials the gateway over mTLS and enforces the L7 policy proxy.</>,
    ours: <>Created by <code>openshell sandbox create</code> in the <code>openshell</code> namespace, on the community OpenClaw sandbox image.</> },
  guard: { id: "guard", label: "Network Guardrail + Privacy Router", sub: "egress + inference.local", color: AMBER,
    what: <>Every outbound connection is checked (deny-by-default, per-binary). The privacy router sends <code>inference.local</code> to a model proxy (LiteLLM), stripping creds + injecting the real key.</>,
    ours: <>Your agent uses a <strong>direct OpenClaw provider config</strong> (<code>openclaw.json</code>) pointed at a remote OpenAI-compatible endpoint (no local GPU) — the policy allows egress only to that host.</> },
  addons: { id: "addons", label: "Optional add-ons", sub: "Envoy · cert-manager · LB · GPU", color: SLATE,
    what: <>Envoy Gateway (Gateway API + GRPCRoute), cert-manager (auto cert rotation), a LoadBalancer Service (external addr + SSH relay), and a GPU device plugin (for GPU sandboxes).</>,
    ours: <>Routes provide external access; CPU-only (no GPU device plugin). The optional monitoring phase adds Prometheus/Grafana/Loki/Tempo.</> },
};

export function OpenShellOnK8s() {
  const [sel, setSel] = useState("gw");
  const a = NODES[sel];
  const Chip = ({ id, w }: { id: string; w?: string }) => {
    const n = NODES[id];
    return (
      <button onClick={() => setSel(id)} className={`rounded-lg border px-2.5 py-1.5 text-left transition ${w ?? "w-full"}`}
        style={{ borderColor: n.color, background: sel === id ? `${n.color}26` : "transparent",
                 boxShadow: sel === id ? `0 0 0 1px ${n.color}` : "none", opacity: sel === id ? 1 : 0.82 }}>
        <div className="text-[12px] font-semibold leading-tight" style={{ color: n.color }}>{n.label}</div>
        {n.sub && <div className="text-[9.5px] text-[var(--color-fg-mut)]">{n.sub}</div>}
      </button>
    );
  };
  const Box = ({ title, children }: { title: string; children: ReactNode }) => (
    <div className="rounded-lg border border-dashed border-[var(--color-line-2)] p-2">
      <div className="mb-1 text-[9px] font-bold uppercase tracking-wide text-[var(--color-fg-mut)]">{title}</div>
      {children}
    </div>
  );

  return (
    <figure className="my-6 rounded-xl border border-[var(--color-line)] bg-[var(--color-panel)] p-4">
      <figcaption className="mb-3 text-sm text-[var(--color-fg-mut)]">OpenShell on Kubernetes — click any object (detail shows how <em>this</em> launchable maps to it)</figcaption>
      <div className="grid gap-2 lg:grid-cols-[150px_1fr_140px]">
        {/* external clients */}
        <div className="flex flex-col gap-2">
          <Box title="clients"><div className="space-y-2"><Chip id="cli" /><Chip id="oidc" /></div></Box>
        </div>
        {/* the cluster */}
        <div className="rounded-xl border-2 p-2" style={{ borderColor: SLATE }}>
          <div className="mb-1 text-[10px] font-bold uppercase tracking-wide" style={{ color: SLATE }}>Kubernetes cluster</div>
          <div className="rounded-lg border-2 p-2" style={{ borderColor: NV }}>
            <div className="mb-1 text-[10px] font-bold" style={{ color: NV }}>namespace: openshell</div>
            <div className="mb-2"><Chip id="grpcroute" /></div>
            <div className="mb-2"><Chip id="gw" /></div>
            <div className="mb-2 grid grid-cols-4 gap-1.5"><Chip id="pvc" /><Chip id="secrets" /><Chip id="rbac" /><Chip id="pki" /></div>
            {/* sandboxes land in the SAME namespace as the gateway (sandboxNamespace: "") */}
            <Chip id="pod" />
          </div>
          <div className="mt-2"><Box title="agent-sandbox-system"><Chip id="ctrl" /></Box></div>
          <div className="mt-2"><Chip id="guard" /></div>
        </div>
        {/* add-ons */}
        <div className="flex flex-col gap-2"><Box title="cluster add-ons"><Chip id="addons" /></Box></div>
      </div>
      <div className="mt-3 rounded-lg border border-[var(--color-line)] bg-[var(--color-bg-2)] p-4 text-sm text-[var(--color-fg-dim)]">
        <div className="mb-1 text-xs font-semibold" style={{ color: a.color }}>{a.label}</div>
        <div className="mb-2">{a.what}</div>
        <div className="rounded border-l-2 pl-2 text-[13px]" style={{ borderColor: NV }}>
          <span className="text-[10px] font-semibold uppercase" style={{ color: NV }}>in this launchable&nbsp;</span>{a.ours}
        </div>
      </div>
    </figure>
  );
}
